apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-deployment
  namespace: socialecho
  labels:
    app: classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
        - name: classifier
          image: ashishguruani/socialecho-classifier-beta:v4
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: classifier-service
  namespace: socialecho
spec:
  type: NodePort
  selector:
    app: classifier
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31200
